@baseUrl = http://localhost:4000/api

# @name get_products
GET {{baseUrl}}/products
Content-Type: application/json

###

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 2
}
